- type: department
  id: SyndicateCommunications
  name: department-SyndicateCommunications
  description: department-SyndicateCommunications-description
  color: "#403010"
  roles:
  - SyndCommOperator
  - SyndCommAgent
  - SyndCommOfficer
  - SyndCommOfficial
#  - CBURNSyndicate
#  - ERTLeaderSyndicate
#  - ERTChaplainSyndicate
#  - ERTJanitorSyndicate
#  - ERTMedicalSyndicate
#  - ERTSecuritySyndicate
#  - ERTEngineerSyndicate
#  editorHidden: true
  weight: -100
