- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Boxer
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: ClothingHandsGlovesBoxingRiggedRed

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChampion
    #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BoxerChameleonOutfit
  job: Boxer
  equipment:
    head: ClothingHeadHatBlacksoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorGray
    jumpsuit: UniformShortsRedWithTop
    neck: ClothingNeckScarfStripedRed
