# Bartender
- type: loadoutGroup
  id: BartenderShoes
  name: loadout-group-bartender-shoes
  loadouts:
  - BlackShoes
  - CombatBoots
  - BrownLeatherShoes
  - LaceupShoes
  - RedHeels
  - BlackHeels
  - BlueHeels
  - GreenHeels
  - HighHeels
  - WinterBoots

- type: loadoutGroup
  parent: [ Glasses ]
  id: BartenderEyewear
  name: loadout-group-bartender-glasses
  minLimit: 0
  loadouts:
  - BeerGlasses
  - BeerEyePatchHud
  - Sunglasses
  - Mirrorshades

# Botanist
- type: loadoutGroup
  id: BotanistShoes
  name: loadout-group-botanist-shoes
  loadouts:
  - BlueShoes
  - BrownShoes
  - GreenShoes
  - CombatBoots
  - BotanistWinterBoots

# Boxer
- type: loadoutGroup
  id: BoxerHead
  name: loadout-group-boxer-head
  minLimit: 0
  loadouts:
  - GladiatorHat
  - KendoHelmet

- type: loadoutGroup
  id: BoxerJumpsuit
  name: loadout-group-boxer-jumpsuit
  loadouts:
  - BoxerShorts
  - BoxerShortsWithTop
  - GladiatorUniform
  - KendoHakama
  - MNKGymBra

- type: loadoutGroup
  id: BoxerBelt
  name: loadout-group-boxer-belt
  minLimit: 0
  loadouts:
  - ChampionBelt

- type: loadoutGroup
  id: BoxerShoes
  name: loadout-group-boxer-shoes
  loadouts:
  - BlackShoes
  - BlueShoes
  - GreenShoes
  - RedShoes
  - YellowShoes
  - CombatBoots

- type: loadoutGroup
  id: BoxerJobTrinkets
  name: loadout-group-jobtrinkets
  minLimit: 0
  loadouts:
  - LizardPlushieBoxer

- type: loadoutGroup
  id: BoxerWeapon
  name: loadout-group-boxer-weapon
  minLimit: 0
  loadouts:
  - RedBoxingGloves
  - BlueBoxingGloves
  - GreenBoxingGloves
  - YellowBoxingGloves
  - Shinai

# Chaplain
- type: loadoutGroup
  id: ChaplainShoes
  name: loadout-group-chaplain-shoes
  loadouts:
  - BlackShoes
  - WhiteShoes
  - CombatBoots
  - LaceupShoes
  - RedHeels
  - BlackHeels
  - HighHeels
  - WinterBoots

- type: loadoutGroup
  id: ChaplainPDAstarcup
  name: loadout-group-chaplain-id-starcup
  loadouts:
  - ChaplainPDA
  - AtheistShepherdPDA
  - DeusDerelictionPDA
  - DruidPDA
  - EpistemicSibylPDA
  - GoshanPreacherPDA
  - GothicCardinalPDA
  - N0taryArtistPDA

- type: loadoutGroup
  id: ChaplainRelic
  name: loadout-group-chaplain-relic
  minLimit: 0
  loadouts:
  - BibleNanoTrasen
  - BibleDruid
  - BibleNarsie
  - BibleCommunistManifesto
  - BibleMisc
  - BibleRatvar
  - BloodVial
  - JanitorLantern
  - PumpkinLantern
  - BikeHorn
  - Wristwatch
  - AnomalyCoreShadowInert
  - AnomalyCoreFleshInert
  - AnomalyCoreTechInert

# Chef
- type: loadoutGroup
  id: ChefShoes
  name: loadout-group-chef-shoes
  loadouts:
  - BlackShoes
  - BrownShoes
  - RedShoes
  - WhiteShoes
  - BrownLeatherShoes
  - LaceupShoes
  - RedHeels
  - BlackHeels
  - ChefWinterBoots

# Clown
- type: loadoutGroup
  id: ClownMask
  name: loadout-group-clown-mask
  minLimit: 0
  loadouts:
  - ClownMask
  - BlushingClownMask
  - RatMask
  - FoxMask
  - BeeMask
  - BearMask
  - RavenMask
  - JackalMask
  - BatMask

# Janitor
- type: loadoutGroup
  id: JanitorBeltstarcup
  name: loadout-group-janitor-belt-starcup
  minLimit: 1
  loadouts:
  - JanitorBelt
  - MaidWaistbag

- type: loadoutGroup
  id: JanitorShoes
  name: loadout-group-janitor-shoes
  loadouts:
  - JanitorGaloshes
  - WhiteShoes
  - BlackShoes
  - LaceupShoes
  - BlackHeels
  - JanitorWinterBoots

- type: loadoutGroup
  id: JanitorLight
  name: loadout-group-janitor-light
  minLimit: 0
  loadouts:
  - JanitorFlashlight
  - JanitorLantern

# Lawyer
- type: loadoutGroup
  id: LawyerOuterClothing
  name: loadout-group-lawyer-outerclothing
  minLimit: 0
  loadouts:
  - WinterCoatBlack
  - WinterCoatBlue

- type: loadoutGroup
  id: LawyerShoes
  name: loadout-group-lawyer-shoes
  loadouts:
  - BrownLeatherShoes
  - LaceupShoes
  - RedHeels
  - BlackHeels
  - BlueHeels
  - WinterBoots

# Librarian
- type: loadoutGroup
  id: LibrarianOuterClothing
  name: loadout-group-librarian-outerclothing
  minLimit: 0
  loadouts:
  - WinterCoatLightBrown
  - WinterCoatBrown

- type: loadoutGroup
  id: LibrarianShoes
  name: loadout-group-librarian-shoes
  loadouts:
  - BlackShoes
  - BrownLeatherShoes
  - LaceupShoes
  - RedHeels
  - BlackHeels
  - GreenHeels
  - WinterBoots

# Mime
- type: loadoutGroup
  id: MimeShoes
  name: loadout-group-mime-shoes
  loadouts:
  - BlackShoes
  - RedShoes
  - WhiteShoes
  - CombatBoots
  - BrownLeatherShoes
  - LaceupShoes
  - MimeWinterBoots

# Musician
- type: loadoutGroup
  id: MusicianShoes
  name: loadout-group-musician-shoes
  loadouts:
  - BlackShoes
  - WhiteShoes
  - BrownLeatherShoes
  - LaceupShoes
  - BlackHeels
  - HighHeels
  - WinterBoots

- type: loadoutGroup
  parent: [ Glasses ]
  id: MusicianEyewear
  name: loadout-group-musician-glasses
  minLimit: 0
  loadouts:
  - Sunglasses
  - Mirrorshades

# Reporter
- type: loadoutGroup
  id: ReporterOuterClothing
  name: loadout-group-reporter-outer-clothing
  minLimit: 0
  loadouts:
  - TrenchCoat

- type: loadoutGroup
  id: ReporterShoes
  name: loadout-group-reporter-shoes
  loadouts:
  - BlackShoes
  - BrownShoes
  - WhiteShoes
  - BrownLeatherShoes
  - LaceupShoes
  - RedHeels
  - BlackHeels
  - WinterBoots

- type: loadoutGroup
  parent: [ Glasses ]
  id: ReporterEyewear
  name: loadout-group-reporter-glasses
  minLimit: 0
  loadouts:
  - Sunglasses
  - Mirrorshades

# Service Worker
- type: loadoutGroup
  id: ServiceWorkerJumpsuit
  name: loadout-group-service-worker-jumpsuit
  loadouts:
  - BartenderJumpsuit
  - BartenderJumpskirt
  - LawyerJumpsuit
  - LawyerJumpskirt
  - JanitorMaidUniform
  - JanitorMaidUniformMini
  - BlackElegantDress
  - GreenElegantDress
  - PurpleElegantDress

- type: loadoutGroup
  id: ServiceWorkerOuterClothing
  name: loadout-group-service-worker-outerclothing
  minLimit: 0
  loadouts:
  - WinterCoatBlack
  - WinterCoatGreen

- type: loadoutGroup
  id: ServiceWorkerShoes
  name: loadout-group-service-worker-shoes
  loadouts:
  - BlackShoes
  - CombatBoots
  - BrownLeatherShoes
  - LaceupShoes
  - BlackHeels
  - GreenHeels
  - HighHeels
  - WinterBoots

- type: loadoutGroup
  parent: [ Glasses ]
  id: ServiceWorkerEyewear
  name: loadout-group-service-worker-glasses
  minLimit: 0
  loadouts:
  - Sunglasses
  - Mirrorshades

# Passenger
- type: loadoutGroup
  parent: [ Glasses ]
  id: PassengerEyewear
  name: loadout-group-passenger-glasses
  minLimit: 0
  loadouts:
  - CheapSunglasses
