# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: NanotrasenOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitNTFormal
    back: ClothingBackpackDuffelNanotrasen
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesColorBlack
    id: NTPDA
    ears: ClothingHeadsetAltNanotrasen

# Nanotrasen Footsoldier Gear - No Headset
- type: startingGear
  id: NanotrasenFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperativeNT
    head: ClothingHeadHelmetSwatNanotrasen
    mask: ClothingMaskGasNanotrasen
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsJack
    id: NTPDA
  storage:
    back:
    - BoxSurvival

# Syndicate Footsoldier Gear
- type: startingGear
  id: NanotrasenFootsoldierGear
  parent: NanotrasenOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperativeNT
    head: ClothingHeadHelmetSwatNanotrasen
    eyes: ClothingEyesHudNanotrasen
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsJackFilled
  storage:
    back:
    - BoxSurvivalNanotrasen

- type: startingGear
  id: NanotrasenFootsoldierTeamLeaderGear
  parent: NanotrasenFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNTFormal
    head: ClothingHeadHatOutlawHat
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSatchel
    pocket1: BaseUplinkRadio25TCNT
    pocket2: EnergySword

# Pet Gear
- type: startingGear
  id: MobMonkeyGearCold
  equipment:
    head: ClothingHeadHatCanadaBeanie
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    outerClothing: ClothingOuterWinterBar
    id: PunPunIDCard

- type: startingGear
  id: MobMimeletGear
  equipment:
    mask: ClothingMaskMime
