- type: job
  id: AdministrativeAssistant
  name: job-name-admin-assistant
  description: job-description-admin-assistant
  playTimeTracker: JobAdminAssistant
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000
  startingGear: AdminAssistantGear
  icon: "JobIconAdminAssitant"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Bar
  - Cargo
  - Cryogenics
  - Engineering
  - External
  - Kitchen
  - Medical
  - Research
  - Service
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: AdminAssistantGear
  equipment:
    belt: ClothingBeltPaperworkFilled
    id: AdminAssistantPDA
    pocket1: RubberStampAdminAssistant
    pocket2: AccessConfigurator
    ears: ClothingHeadsetCommandSyndie
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: AdminAssistantChameleonOutfit
  job: AdministrativeAssistant
  equipment:
    Head: ClothingHeadHatCommandSoftSyndie
    Eyes: ClothingEyesHudCommandSyndie
    Mask: ClothingMaskBreath
    Neck: ClothingNeckScarfStripedPurple
    OuterClothing: ClothingOuterVest
    Gloves: ClothingHandsGlovesHop
